baseURL = "https://kaunghko.github.io/"
languageCode = "en-us"
title = "Htet Ko's Portfolio"
theme = "PaperMod"

[params]
author = "Kaung Htet Ko"
description = "My blog about software engineering and machine learning."
# For a professional look
defaultTheme = "auto" # or "light" or "dark"
ShowShareButtons = true
ShowReadingTime = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    identifier = "experiences"
    name = "Experiences"
    url = "/experiences/"
    weight = 20
  [[menu.main]]
    identifier = "certificates"
    name = "Certificates"
    url = "/certificates/"
    weight = 30